name: Maven build and release

on:
  push: [main, snapshot]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run Maven
        run: mvn package source:jar javadoc:jar deploy
