name: Maven release

on:
  push:
    branches: [main, snapshot]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 14
          distribution: 'adopt'
      - name: Run Maven
        run: mvn package source:jar javadoc:jar deploy
