name: Maven verify

on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Maven
        run: mvn --batch-mode --upgrade-snapshots package javadoc:javadoc verify
