name: Maven verify

on:
  push: [main, snapshot]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Run Maven
        run: mvn package javadoc:javadoc
